### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by aliisakroe** [JarrettPhilips/Philips_CSCI2270_FinalProject#1]
It might be a good idea to put checks on what the user can enter while setting up the game. For example, if the user types characters for the amount of money will result in a segfault, or putting a large number for the number of players (1000000) means that a single round would have to take a proportional number turns (it does turn out that actually segfaults before that). 

I think another such segfault may be due to not setting custom struct variables to NULL initially,  since that is what is being checked in the conditionals.

Since players are being dynamically allocated (explicit memory), it is also important to explicitly clear that memory by `delete []` ing such variables initialized with `new` . This may clear up a segfault, may not.

**Comment by JarrettPhilips** [comment]
Fixed with aliisakroe's patch.
